# List of DB Ports to compile MADlib for.
#
# Synopsis:
# - name   : descriptive name of the new DB port
#

postgres:
    name:   PostgreSQL

greenplum:
    name:   Greenplum DB

pieclouddb:
    name:   PieCloudDB
